using Content.Shared._NF.Bank.Components;
using Content.Shared._WH40K.Merchant;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client._WH40K.Merchant;

[GenerateTypedNameReferences]
public sealed partial class MerchantWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private readonly List<MerchantOfferControl> _offerControls = new();
    private TimeSpan _refreshAt;
    private int _balance;

    public event Action<string>? OnBuy;
    public event Action? OnRequestRefresh;

    public MerchantWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnRequestRefresh?.Invoke();
    }

    public void UpdateState(MerchantUpdateState state, int balance)
    {
        Title = Loc.GetString(state.Title);
        MerchantTitle.Text = Title;
        GreetingLabel.SetMessage(Loc.GetString(state.Greeting), new Color(214, 220, 225));
        CycleLabel.Text = Loc.GetString("wh40k-merchant-cycle", ("number", state.RefreshNumber));

        _balance = balance;
        _refreshAt = _timing.CurTime + TimeSpan.FromSeconds(state.RefreshInSeconds);
        RebuildOffers(state.Offers);
        UpdateHeader();
    }

    public void UpdateBalance(int balance)
    {
        if (_balance == balance)
            return;

        _balance = balance;
        foreach (var control in _offerControls)
            control.UpdateAffordability(_balance);
        UpdateHeader();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_playerManager.LocalEntity is { } local
            && _entityManager.TryGetComponent<BankAccountComponent>(local, out var bank))
        {
            UpdateBalance(bank.Balance);
        }

        UpdateHeader();
    }

    private void RebuildOffers(IReadOnlyList<MerchantOfferState> offers)
    {
        foreach (var control in _offerControls)
            control.Dispose();

        _offerControls.Clear();
        OffersContainer.Children.Clear();

        var sprites = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
        foreach (var offer in offers)
        {
            Texture? icon = null;
            if (_prototypes.TryIndex<EntityPrototype>(offer.Product, out _))
                icon = sprites.GetPrototypeIcon(new EntProtoId(offer.Product)).Default;

            var control = new MerchantOfferControl(offer, icon);
            control.OnBuy += productId => OnBuy?.Invoke(productId);
            control.UpdateAffordability(_balance);
            _offerControls.Add(control);
            OffersContainer.AddChild(control);
        }

        FooterLabel.Text = offers.Count == 0
            ? Loc.GetString("wh40k-merchant-empty")
            : Loc.GetString("wh40k-merchant-footer");
    }

    private void UpdateHeader()
    {
        BalanceLabel.Text = Loc.GetString("wh40k-merchant-balance", ("amount", _balance));
        var seconds = Math.Max(0, (int)Math.Ceiling((_refreshAt - _timing.CurTime).TotalSeconds));
        RefreshLabel.Text = Loc.GetString("wh40k-merchant-refresh", ("seconds", seconds));
    }
}

internal sealed class MerchantOfferControl : PanelContainer
{
    private readonly MerchantOfferState _offer;
    private readonly Button _buyButton;
    private readonly Label _stockLabel;
    private readonly int _price;

    public event Action<string>? OnBuy;

    public MerchantOfferControl(MerchantOfferState offer, Texture? icon)
    {
        _offer = offer;
        _price = offer.Price;
        MinHeight = 86;
        Margin = new Thickness(0, 0, 0, 8);
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(18, 24, 30, 245),
            BorderColor = new Color(105, 82, 46),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 8,
            ContentMarginBottomOverride = 8
        };

        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        AddChild(row);

        var texture = new TextureRect
        {
            Texture = icon,
            MinSize = new Vector2(64, 64),
            MaxSize = new Vector2(64, 64),
            Stretch = TextureRect.StretchMode.KeepAspectCentered
        };
        row.AddChild(texture);

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(12, 0, 8, 0)
        };
        row.AddChild(text);

        var name = new Label
        {
            Text = ResolveName(offer),
            FontColorOverride = new Color(227, 207, 165)
        };
        text.AddChild(name);

        var description = new Label
        {
            Text = ResolveDescription(offer),
            FontColorOverride = new Color(165, 174, 184),
            ClipText = true,
            HorizontalExpand = true
        };
        text.AddChild(description);

        _stockLabel = new Label { FontColorOverride = new Color(141, 188, 151) };
        text.AddChild(_stockLabel);

        _buyButton = new Button { MinWidth = 138, MinHeight = 42 };
        _buyButton.OnPressed += _ => OnBuy?.Invoke(_offer.Product);
        row.AddChild(_buyButton);
    }

    public void UpdateAffordability(int balance)
    {
        _stockLabel.Text = Loc.GetString("wh40k-merchant-stock", ("remaining", _offer.Remaining), ("maximum", _offer.MaxStock));
        _buyButton.Text = Loc.GetString("wh40k-merchant-buy", ("price", _price));
        _buyButton.Disabled = _offer.Remaining <= 0 || balance < _price;
    }

    private static string ResolveName(MerchantOfferState offer)
    {
        if (!string.IsNullOrWhiteSpace(offer.DisplayName))
            return Loc.GetString(offer.DisplayName);

        return offer.Product;
    }

    private static string ResolveDescription(MerchantOfferState offer)
    {
        if (!string.IsNullOrWhiteSpace(offer.Description))
            return Loc.GetString(offer.Description);

        return Loc.GetString("wh40k-merchant-generic-description");
    }
}
